### ISSUE TITLE
Bug Report: [Several Issues Really]

### ISSUE THREAD

**Issue by RodneyAnImaginativePerson** [MobilePorting/CodenameEngine-Mobile#1]
- ~~Pressing the back arrow doesn't pause the song.~~ - Fixed by lily
- Can't change control layout at all.
- Current control option doesn't appear at all in PlayState.
- Freeplay seems to be busted as the difficulty is set to "-" as well as pressing A doing nothing.
- ~~GameOverState has no way to leave.~~ - Fixed by lily
- If you change controls for keyboard you get softlocked changing the bind for A.

**Comment by moxie-coder** [comment]
noted

**Comment by moxie-coder** [comment]
are you on the latest version?

**Comment by RodneyAnImaginativePerson** [comment]
Yes

**Comment by RodneyAnImaginativePerson** [comment]
> are you on the latest version?

I am using the latest action build.

**Comment by moxie-coder** [comment]
alright well, unless @mcagabe19 knows anything about this, I'll keep these in mind

**Comment by mcagabe19** [comment]
cne port is still wip so except these

**Comment by RodneyAnImaginativePerson** [comment]
> cne port is still wip so except these

Huh, I say this because I've seen videos of this exact port working fine in PlayState.s

**Comment by mcagabe19** [comment]
karim fixed other issues so closing

**Comment by KarimAkra** [comment]
I don't think i fixed the last one abt changing keybind controls for keyboard

**Comment by mcagabe19** [comment]
@KarimAkra can u tell to testers test our cne port in both iOS and android latest actions build at tester-channel? vpn not working

**Comment by Nyleh** [comment]
I can't access songs on Freeplay

**Comment by Nyleh** [comment]
I used yesterday's build
