### ISSUE TITLE
Bug Report: [In Change Controls Pause Week6]

### ISSUE THREAD

**Issue by levi-go64** [MobilePorting/CodenameEngine-Mobile#10]
[In pause Week 6 In Change Controls, Can't Press Save & Exit and left & right in above left]
[Android]
![Screenshot_20240414_100552](https://github.com/MobilePorting/CodenameEngine-Mobile/assets/96037133/3cba79aa-cff8-482a-8348-68170ff8b58c)

**Comment by mcagabe19** [comment]
@moxie-coder this issue not fixed yet don't close

**Comment by moxie-coder** [comment]
> @moxie-coder this issue not fixed yet don't close

sorry hun
