### ISSUE TITLE
Crash for mobile crash 

### ISSUE THREAD

**Issue by Faeyzaf** [MobilePorting/CodenameEngine-Mobile#15]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[ ] Windows
[ ] Linux
[ ] Mac
[X]mobile

##### Please check first if your issue haven't already been reported yet.
[weed]: <> (MAKE SURE TO ADD A SCREENSHOT OF THE CRASH HANDLER, IF AVAILABLE, AND STEPS TO REPRODUCE THE BUG!)

**Comment by Faeyzaf** [comment]
Done

**Comment by mcagabe19** [comment]
*sigh* u didn't write a crash reason

**Comment by SkyBaoFall** [comment]
Blud  Lazy to Say Issue

**Comment by mcagabe19** [comment]
closing no response
