### ISSUE TITLE
The game crashed when I enter The game folder pd: is created but the folders inside like ._sol are not created

### ISSUE THREAD

**Issue by Amaya26788** [MobilePorting/CodenameEngine-Mobile#16]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[ ] Windows
[ ] Linux
[ ] Mac

##### Please check first if your issue haven't already been reported yet.
[weed]: <> (MAKE SURE TO ADD A SCREENSHOT OF THE CRASH HANDLER, IF AVAILABLE, AND STEPS TO REPRODUCE THE BUG!)

**Comment by moxie-coder** [comment]
we need more info, saying the game crashed doesn't do shit for us

**Comment by moxie-coder** [comment]
not in the title retard, learn to use GitHub
