### ISSUE TITLE
Suggestion to Improve Performance 

### ISSUE THREAD

**Issue by ElDoradoGamer6** [MobilePorting/CodenameEngine-Mobile#17]
## What is your suggestion, and why should it be implemented?
I would like them to add the CPU Caching option that the Psych Engine has since there are some devices that do not have a good amount of ram memory but do have a good processor and I think it would be a good idea to add that option to improve performance on the devices aforementioned 
(note: it is only a recommendation, I am not forcing you to do anything, if you decide to do so it is your decision) 
No more for the moment, I say goodbye :)

**Comment by moxie-coder** [comment]
it’s gpu caching, and it already exists, this shit is as optimized as it can be

**Comment by mcagabe19** [comment]
stupid there's no CPU caching on psch it's GPU
