### ISSUE TITLE
Bug Report: [import mods]

### ISSUE THREAD

**Issue by Sonk998** [MobilePorting/CodenameEngine-Mobile#20]
[weed]: <> how do I import mods? For example, the psych engine port makes you need to make a folder And place the assets+mods folder there to Import mods for that. How exactly do I do that for this engine?

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[ ] Windows
[ ] Linux
[ ] Mac
[X ] MOBILE

**Comment by SkyBaoFall** [comment]
mods/
