### ISSUE TITLE
Codename Engine crashing

### ISSUE THREAD

**Issue by SK7580** [MobilePorting/CodenameEngine-Mobile#21]
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[ ] Windows
[ ] Linux
[ ] Mac
[ x] Android
[ ] iOS

##### Whenever I open it, it just crashing for me
[weed]: > (MAKE SURE TO ADD A SCREENSHOT OF THE CRASH HANDLER, IF AVAILABLE, AND !)

**Comment by moxie-coder** [comment]
wow, thanks for giving us nothing to fucking work with

**Comment by moxie-coder** [comment]
start actually giving out info

**Comment by SK7580** [comment]
If did it now

**Comment by moxie-coder** [comment]
> I did it now

again, that says nothing, we need logs, anything like that

**Comment by SK7580** [comment]
https://github.com/MobilePorting/CodenameEngine-Mobile/assets/134719321/052ccd64-019d-4718-95a0-ee5c383b6840

This is the problem actually

**Comment by mcagabe19** [comment]
new devbuild needed to be released but we're busy, wait till 3 PM (GMT+3)
