### ISSUE TITLE
Bug Report: can't mod with it.

### ISSUE THREAD

**Issue by Drago-Cuven** [MobilePorting/CodenameEngine-Mobile#22]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[ ] Windows
[ ] Linux
[ ] Mac
[x] Android
[x] ChromeOS (Android)
[ ] ChromeOS (Linux)
[ ] iOS

### Explain your issue
the button 7 doesn't work anymore, preventing me from accessing the menus like the chart menu. keeping me from modding in any way shape or form.
##### Please check first if your issue haven't already been reported yet.
[weed]: <> (MAKE SURE TO ADD A SCREENSHOT OF THE CRASH HANDLER, IF AVAILABLE, AND STEPS TO REPRODUCE THE BUG!)

**Comment by mcagabe19** [comment]
? send a video what r u doing

**Comment by mcagabe19** [comment]
@Drago-Cuven just use crostini and download linux builds of cne (consider using box64 if ur cpu is aarch64)
