### ISSUE TITLE
You Can't Add Instrumentals And Vocals

### ISSUE THREAD

**Issue by TotallyReliableDino** [MobilePorting/CodenameEngine-Mobile#23]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[ ] Windows
[ ] Linux
[ ] Mac
[x] Android
[ ] iOS

##### Please check first if your issue haven't already been reported yet.
[weed]: <> (MAKE SURE TO ADD A SCREENSHOT OF THE CRASH HANDLER, IF AVAILABLE, AND STEPS TO REPRODUCE THE BUG!)
You can't Add Vocals And Instruments Through The New Song Option in The Charts Editor

**Comment by moxie-coder** [comment]
that doesn’t say a lot

**Comment by mcagabe19** [comment]
wontfix
