### ISSUE TITLE
Bug Report: [DESCRIBE YOUR BUG IN DETAIL HERE] I put the new FNF mod named ,,Underverse_Funk", I opened it and I can't enter anything. It just blocks me on the menu screen. I am on Android 11

### ISSUE THREAD

**Issue by bonniegirlezy** [MobilePorting/CodenameEngine-Mobile#24]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[ ] Windows
[ ] Linux
[ ] Mac
[ ] Android
[ ] iOS

##### Please check first if your issue haven't already been reported yet.
[weed]: <> (MAKE SURE TO ADD A SCREENSHOT OF THE CRASH HANDLER, IF AVAILABLE, AND STEPS TO REPRODUCE THE BUG!)

**Comment by moxie-coder** [comment]
firstly, make sure you put your issue in the *description* not the title, secondly that mod may be need to be ported
