### ISSUE TITLE
Enhancement: Editor on Mobile

### ISSUE THREAD

**Issue by megalives717** [MobilePorting/CodenameEngine-Mobile#27]
![Screenshot_20241215-165019](https://github.com/user-attachments/assets/102d7ed2-7af8-422a-b8d3-0f9ad1e7691f)
![Screenshot_20241215-165036](https://github.com/user-attachments/assets/9c111597-f075-4020-915e-da4e0192df47)
Why I Can't Use Editor on Mobile?

**Comment by mcagabe19** [comment]
connect a keyboard and mouse to ur phone and set controls alpha 0

**Comment by megalives717** [comment]
> connect a keyboard and mouse to ur phone and set controls alpha 0

I Don't Have to Connect Keyboard and Mouse

**Comment by mcagabe19** [comment]
nothing I can do
