### ISSUE TITLE
Bug Report: Stuck on Title Screen after set Controls Alpha to 0

### ISSUE THREAD

**Issue by megalives717** [MobilePorting/CodenameEngine-Mobile#29]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[ ] Windows
[ ] Linux
[ ] Mac
[x] Android
[ ] iOS

##### I Got Stuck on a Title Screen In Controls Alpha 0
[weed]: <> (MAKE SURE TO ADD A SCREENSHOT OF THE CRASH HANDLER, IF AVAILABLE, AND STEPS TO REPRODUCE THE BUG!)

**Comment by megalives717** [comment]
Please Don't Close Reopen It

**Comment by moxie-coder** [comment]
> Please Don't Close Reopen It

it was fixed moron
