### ISSUE TITLE
Compiling help: Android

### ISSUE THREAD

**Issue by megalives717** [MobilePorting/CodenameEngine-Mobile#30]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[x] Windows
[ ] Linux
[ ] Mac
[ ] Android
[ ] iOS

##### I run command `lime build android` but have problem
[weed]: <> (MAKE SURE TO ADD A SCREENSHOT OF THE CRASH HANDLER, IF AVAILABLE, AND STEPS TO REPRODUCE THE BUG!)

**Comment by mcagabe19** [comment]
make sure u runned `haxe -cp commandline -D analyzer-optimize --run Main setup -s --lib=./libs.mobile.xml`

**Comment by mcagabe19** [comment]
and have latest ndk, jdk 17 and sdk build tools 25

**Comment by moxie-coder** [comment]
tells us he as a problem but doesn't **show the problem**
