### ISSUE TITLE
Enhancement: Mobile Chart/Character/Stage Editor Support

### ISSUE THREAD

**Issue by megalives717** [MobilePorting/CodenameEngine-Mobile#31]

**Comment by mcagabe19** [comment]
duplicate of #27

**Comment by megalives717** [comment]
PLEASE REOPEN TO MAKE MOBILE EDITOR SUPPORT!!!

**Comment by moxie-coder** [comment]
> PLEASE REOPEN TO MAKE MOBILE EDITOR SUPPORT!!!

please learn what a duplicate is and stop being fucking annoying
