### ISSUE TITLE
Compiling help: Cannot process [flixel]: Library flixel is not installed : run 'haxelib install flixel' Error

### ISSUE THREAD

**Issue by megalives717** [MobilePorting/CodenameEngine-Mobile#32]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[x] Windows
[ ] Linux
[ ] Mac
[ ] Android
[ ] iOS

##### ![issue](https://github.com/user-attachments/assets/c9acd666-4659-4916-b851-c70094afc76c)
help

**Comment by megalives717** [comment]
pls help

**Comment by mcagabe19** [comment]
can u run update.bat
