### ISSUE TITLE
What happened to the action builds?

### ISSUE THREAD

**Issue by RodneyAnImaginativePerson** [MobilePorting/CodenameEngine-Mobile#4]
I was gonna test out the latest version of this when I discovered the actions tab was empty. There are no build whatsoever, it really confused me.

**Comment by mcagabe19** [comment]
we use laptops for build and cne is still on beta state so except it

**Comment by RodneyAnImaginativePerson** [comment]
> we use laptops for build and cne is still on beta state so except it

I thought github would've complied something lol
