### ISSUE TITLE
Bug Report: [GAME WON'T OPEN + A ACTUAL BUG]

### ISSUE THREAD

**Issue by RefuestJeremiah** [MobilePorting/CodenameEngine-Mobile#5]
I was waiting for the main build to finish and then when Androidbuild was finish i downloaded it then it INSTANTLY CRASHED

Also I am sorry for Asking how to download Codename Engine 

- Refuest Jeremiah

**Comment by mcagabe19** [comment]
which build you downloaded? (EXTERNAL, MEDIA, OBB or DATA)

**Comment by RefuestJeremiah** [comment]
External

**Comment by mcagabe19** [comment]
yeah we removed EXTERNAL and MEDIA
