### ISSUE TITLE
Bug Report: [Error Issue In Story Mode Week6]

### ISSUE THREAD

**Issue by levi-go64** [MobilePorting/CodenameEngine-Mobile#6]
[When The Dialogue Is Done, suddenly there was an error.]

[Uploading Screenshot_20240407_142357.jpg…]

**Comment by levi-go64** [comment]
![Uploading Screenshot_20240407_142357.jpg…]()

**Comment by mcagabe19** [comment]
can u try this after build finishes?
https://github.com/MobilePorting/CodenameEngine-Mobile/actions/runs/8587153902

**Comment by levi-go64** [comment]
![Screenshot_20240407_142357](https://github.com/MobilePorting/CodenameEngine-Mobile/assets/96037133/0cc5714b-7cec-4a85-971b-6135271ed4bd)

**Comment by levi-go64** [comment]
> can u try this after build finishes? https://github.com/MobilePorting/CodenameEngine-Mobile/actions/runs/8587153902

Sure

**Comment by levi-go64** [comment]
It still error @mcagabe19 

![Screenshot_20240407_185509](https://github.com/MobilePorting/CodenameEngine-Mobile/assets/96037133/a15f1b03-7d1f-4b4b-adde-d8996b7435d8)

**Comment by mcagabe19** [comment]
try deleting assets and copy to `Android/(data or obb)/com.yoshman29.codenameengine`

**Comment by levi-go64** [comment]
Also i found this bug

![Screenshot_20240407_185435](https://github.com/MobilePorting/CodenameEngine-Mobile/assets/96037133/509a42dd-7941-4d61-bb4e-e6ec4a6ddbea)


When go to options and back again to main menu, the virtualpad is gone, but can still press

**Comment by levi-go64** [comment]
> try deleting assets and copy it again (path is `Android/(data or obb)/com.yoshman29.codenameengine`)

Okay

**Comment by mcagabe19** [comment]
> Also i found this bug
> 
> ![Screenshot_20240407_185435](https://private-user-images.githubusercontent.com/96037133/320279200-509a42dd-7941-4d61-bb4e-e6ec4a6ddbea.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0OTE0ODIsIm5iZiI6MTcxMjQ5MTE4MiwicGF0aCI6Ii85NjAzNzEzMy8zMjAyNzkyMDAtNTA5YTQyZGQtNzk0MS00ZDYxLWJiNGUtZTZlYzRhNmRkYmVhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDExNTk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyZTVkNWI5OTY0MzY0YWMwOGU0M2Y0NjcyMDFiYjM5ZTgxNjg2YThiNjY2ZjU4MmUyNWI4OGU4OTU5YzM1YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MxsWWI-njtDp52oBCbBBO8ZfjvLLOcvm7TSGE-8jB_0)
> 
> When go to options and back again to main menu, the virtualpad is gone, but can still press

that's a known bug

**Comment by levi-go64** [comment]
Wait now is working, thanks for telling me
