### ISSUE TITLE
Bug Report: android controls in mods not working 

### ISSUE THREAD

**Issue by ElDoradoGamer6** [MobilePorting/CodenameEngine-Mobile#7]
https://github.com/MobilePorting/CodenameEngine-Mobile/assets/121194869/8d8d4027-95c5-4776-b26b-83a26a8e5c82

[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[ ] Windows
[ ] Linux
[ ] Mac
[X] Android

##### When placing mods in codename engine like Gorefield which have custom menus, the buttons that should appear for Android do not appear so I have to resort to using a keyboard or an external keyboard application to be able to move through the menus.
If there is a word that has been spelled wrong, it's not me, it's because I'm using a Spanish to English translator, so if you don't understand some of the words, it's because of the translator :) GOOD BYE

**Comment by moxie-coder** [comment]
you have to port it yourself, it doesn’t work automatically on android

**Comment by ElDoradoGamer6** [comment]
Isn't there any code I can write in the menu script to make the mobile controls appear?

**Comment by moxie-coder** [comment]
idk, I can't help with android ports atm, only iOS

**Comment by ElDoradoGamer6** [comment]
ah ok it doesn't matter, thank you anyway and sorry for the inconvenience :)

**Comment by moxie-coder** [comment]
np
