### ISSUE TITLE
I downloaded a mod but it says I have to press enter and I'm touching the screen and it won't let me enter the modBug Report: [DESCRIBE YOUR BUG IN DETAIL HERE]

### ISSUE THREAD

**Issue by Endlessuser300** [MobilePorting/CodenameEngine-Mobile#8]
The port works but the error when pressing enter needs to be fixed [weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[ ] Windows
[ ] Linux
[ ] Mac

##### Please check first if your issue haven't already been reported yet.
[weed]: <> (MAKE SURE TO ADD A SCREENSHOT OF THE CRASH HANDLER, IF AVAILABLE, AND STEPS TO REPRODUCE THE BUG!)

**Comment by moxie-coder** [comment]
I understand nothing from this

**Comment by moxie-coder** [comment]
![intro-1614549012](https://github.com/MobilePorting/CodenameEngine-Mobile/assets/124418090/974feae0-5d69-49d1-96f2-ae418f0d7301)

**Comment by Endlessuser300** [comment]
If it doesn't let me in and I'm touching the phone screen

**Comment by moxie-coder** [comment]
> If it doesn't let me in and I'm touching the phone screen

then it's a mod that doesn't support mobile, and you need to port it yourself
